import styles from'./Layout.module.scss';
import Head from 'next/head';
import Menu from './Menu'

export default function Layout(props) {
    return (
        <div className={styles.layout}>
            <Head>
                <title>領養代替購買</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.svg" />
            </Head>
            <Menu/>
            <main className={styles.main}>{props.children}</main>
        </div>
    )
}
